// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: prefer_single_quotes, public_member_api_docs, lines_longer_than_80_chars, implicit_dynamic_list_literal, implicit_dynamic_map_literal

import 'package:mason/mason.dart';

final dartFileBundle = MasonBundle.fromJson(<String, dynamic>{
  "files": [
    {
      "path": "{{name.snakeCase()}}.dart",
      "data":
          "aW1wb3J0ICdkYXJ0OmNvbnZlcnQnOwppbXBvcnQgJ2RhcnQ6dHlwZWRfZGF0YSc7CgppbXBvcnQgJ2RhcnQ6dWknOwoKaW1wb3J0ICdwYWNrYWdlOnVtYnJhX2ZsdXR0ZXIvdW1icmFfZmx1dHRlci5kYXJ0JzsKCi8vLyB7QHRlbXBsYXRlIHt7bmFtZS5zbmFrZUNhc2UoKX19fQovLy8gQSBEYXJ0IFNoYWRlciBjbGFzcyBmb3IgdGhlIGB7e25hbWV9fWAgc2hhZGVyLgovLy8ge0BlbmR0ZW1wbGF0ZX0KY2xhc3Mge3tuYW1lLnBhc2NhbENhc2UoKX19IGV4dGVuZHMgVW1icmFTaGFkZXIgewogIHt7bmFtZS5wYXNjYWxDYXNlKCl9fS5fKCkgOiBzdXBlcihfY2FjaGVkUHJvZ3JhbSEpOwoKICAvLy8ge0BtYWNybyB7e25hbWUuc25ha2VDYXNlKCl9fX0KICBzdGF0aWMgRnV0dXJlPHt7bmFtZS5wYXNjYWxDYXNlKCl9fT4gY29tcGlsZSgpIGFzeW5jIHsKICAgIC8vIENhY2hpbmcgdGhlIHByb2dyYW0gb24gdGhlIGZpcnN0IGNvbXBpbGUgY2FsbC4KICAgIF9jYWNoZWRQcm9ncmFtID8/PSBhd2FpdCBGcmFnbWVudFByb2dyYW0uY29tcGlsZSgKICAgICAgc3BpcnY6IFVpbnQ4TGlzdC5mcm9tTGlzdChiYXNlNjREZWNvZGUoX3NwaXJ2KSkuYnVmZmVyLAogICAgKTsKCiAgICByZXR1cm4ge3tuYW1lLnBhc2NhbENhc2UoKX19Ll8oKTsKICB9CgogIHN0YXRpYyBGcmFnbWVudFByb2dyYW0/IF9jYWNoZWRQcm9ncmFtOwoKICBTaGFkZXIgc2hhZGVyKHsKICAgIHJlcXVpcmVkIFNpemUgcmVzb2x1dGlvbix7eyNwYXJhbWV0ZXJzfX0KICAgIHJlcXVpcmVkIHt7dHlwZX19IHt7bmFtZS5jYW1lbENhc2UoKX19LHt7L3BhcmFtZXRlcnN9fQogIH0pIHsKICAgIHJldHVybiBwcm9ncmFtLnNoYWRlcigKICAgICAgZmxvYXRVbmlmb3JtczogRmxvYXQzMkxpc3QuZnJvbUxpc3QoW3t7I2FyZ3VtZW50c319CiAgICAgICAge3tuYW1lLmNhbWVsQ2FzZSgpfX17e2V4dGVuc2lvbn19LHt7L2FyZ3VtZW50c319CiAgICAgICAgcmVzb2x1dGlvbi53aWR0aCwKICAgICAgICByZXNvbHV0aW9uLmhlaWdodCwKICAgICAgXSksCiAgICAgIHNhbXBsZXJVbmlmb3JtczogW3t7I3NhbXBsZXJzfX0KICAgICAgICBJbWFnZVNoYWRlcigKICAgICAgICAgIHt7bmFtZS5jYW1lbENhc2UoKX19e3tleHRlbnNpb259fSwKICAgICAgICAgIFRpbGVNb2RlLmNsYW1wLAogICAgICAgICAgVGlsZU1vZGUuY2xhbXAsCiAgICAgICAgICBVbWJyYVNoYWRlci5pZGVudGl0eSwKICAgICAgICApLAogICAgICAgIHt7L3NhbXBsZXJzfX0KICAgICAgXSwKICAgICk7CiAgfQp9Cgpjb25zdCBfc3BpcnYgPQogICAge3t7c3BpcnZCeXRlc319fTsK",
      "type": "text"
    }
  ],
  "hooks": [],
  "name": "dart_file",
  "description": "Generate a Dart Shader file for a Flutter GLSL shader.",
  "version": "0.1.0+1",
  "environment": {"mason": ">=0.1.0-dev <0.1.0"},
  "vars": {}
});
