// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: prefer_single_quotes, public_member_api_docs, lines_longer_than_80_chars, implicit_dynamic_list_literal, implicit_dynamic_map_literal

import 'package:mason/mason.dart';

final flutterWidgetFileBundle = MasonBundle.fromJson(<String, dynamic>{
  "files": [
    {
      "path": "{{name.snakeCase()}}.dart",
      "data":
          "aW1wb3J0ICdkYXJ0OmNvbnZlcnQnOwppbXBvcnQgJ2RhcnQ6dHlwZWRfZGF0YSc7CmltcG9ydCAnZGFydDp1aSc7CgppbXBvcnQgJ3BhY2thZ2U6Zmx1dHRlci9tYXRlcmlhbC5kYXJ0JyBoaWRlIEltYWdlOwppbXBvcnQgJ3BhY2thZ2U6dW1icmFfZmx1dHRlci91bWJyYV9mbHV0dGVyLmRhcnQnOwoKLy8vIHtAdGVtcGxhdGUge3tuYW1lLnNuYWtlQ2FzZSgpfX19Ci8vLyBBIEZsdXR0ZXIgV2lkZ2V0IGZvciB0aGUgYHt7bmFtZX19YCBzaGFkZXIuCi8vLyB7QGVuZHRlbXBsYXRlfQpjbGFzcyB7e25hbWUucGFzY2FsQ2FzZSgpfX0gZXh0ZW5kcyBTdGF0ZWxlc3NXaWRnZXQgewogIC8vLyB7QG1hY3JvIHt7bmFtZS5zbmFrZUNhc2UoKX19fQogIGNvbnN0IHt7bmFtZS5wYXNjYWxDYXNlKCl9fSh7CiAgICBLZXk/IGtleSwKICAgIEJsZW5kTW9kZSBibGVuZE1vZGUgPSBCbGVuZE1vZGUuc3JjLHt7I3BhcmFtZXRlcnN9fQogICAgcmVxdWlyZWQge3t0eXBlfX0ge3tuYW1lLmNhbWVsQ2FzZSgpfX0se3svcGFyYW1ldGVyc319CiAgfSkgIDogX2JsZW5kTW9kZSA9IGJsZW5kTW9kZSx7eyNwYXJhbWV0ZXJzfX0KICAgICAgICBfe3tuYW1lLmNhbWVsQ2FzZSgpfX0gPSB7e25hbWUuY2FtZWxDYXNlKCl9fSx7ey9wYXJhbWV0ZXJzfX0KICAgICAgICBzdXBlcihrZXk6IGtleSk7CgogIHN0YXRpYyBGdXR1cmU8RnJhZ21lbnRQcm9ncmFtPj8gX2NhY2hlZFByb2dyYW07CgogIGZpbmFsIEJsZW5kTW9kZSBfYmxlbmRNb2RlOwp7eyNwYXJhbWV0ZXJzfX0KICBmaW5hbCB7e3R5cGV9fSBfe3tuYW1lLmNhbWVsQ2FzZSgpfX07Cnt7L3BhcmFtZXRlcnN9fQogIEBvdmVycmlkZQogIFdpZGdldCBidWlsZChCdWlsZENvbnRleHQgY29udGV4dCkgewogICAgcmV0dXJuIEZ1dHVyZUJ1aWxkZXI8RnJhZ21lbnRQcm9ncmFtPigKICAgICAgZnV0dXJlOiBfY2FjaGVkUHJvZ3JhbSA/PwogICAgICAgICAgRnJhZ21lbnRQcm9ncmFtLmNvbXBpbGUoCiAgICAgICAgICAgIHNwaXJ2OiBVaW50OExpc3QuZnJvbUxpc3QoYmFzZTY0RGVjb2RlKF9zcGlydikpLmJ1ZmZlciwKICAgICAgICAgICksCiAgICAgIGJ1aWxkZXI6IChjb250ZXh0LCBzbmFwc2hvdCkgewogICAgICAgIGlmIChzbmFwc2hvdC5oYXNFcnJvcikgewogICAgICAgICAgLy8gVE9ETzogQWRkIGEgZXJyb3IgYnVpbGRlcj8KICAgICAgICAgIHJldHVybiBUZXh0KCcke3NuYXBzaG90LmVycm9yfScpOwogICAgICAgIH0KICAgICAgICBpZiAoIXNuYXBzaG90Lmhhc0RhdGEpIHsKICAgICAgICAgIC8vIFRPRE86IEFkZCBhIGxvYWRpbmcgYnVpbGRlcj8KICAgICAgICAgIHJldHVybiBjb25zdCBDaXJjdWxhclByb2dyZXNzSW5kaWNhdG9yKCk7CiAgICAgICAgfQogICAgICAgIGZpbmFsIHByb2dyYW0gPSBzbmFwc2hvdC5kYXRhITsKCiAgICAgICAgcmV0dXJuIExheW91dEJ1aWxkZXIoCiAgICAgICAgICBidWlsZGVyOiAoY29udGV4dCwgY29uc3RyYWludHMpIHsKICAgICAgICAgICAgcmV0dXJuIFNoYWRlck1hc2soCiAgICAgICAgICAgICAgYmxlbmRNb2RlOiBfYmxlbmRNb2RlLAogICAgICAgICAgICAgIHNoYWRlckNhbGxiYWNrOiAoYm91bmRzKSB7CiAgICAgICAgICAgICAgICByZXR1cm4gcHJvZ3JhbS5zaGFkZXIoCiAgICAgICAgICAgICAgICAgIGZsb2F0VW5pZm9ybXM6IEZsb2F0MzJMaXN0LmZyb21MaXN0KFt7eyNhcmd1bWVudHN9fQogICAgICAgICAgICAgICAgICAgIF97e25hbWUuY2FtZWxDYXNlKCl9fXt7ZXh0ZW5zaW9ufX0se3svYXJndW1lbnRzfX0KICAgICAgICAgICAgICAgICAgICBib3VuZHMuc2l6ZS53aWR0aCwgCiAgICAgICAgICAgICAgICAgICAgYm91bmRzLnNpemUuaGVpZ2h0LAogICAgICAgICAgICAgICAgICBdKSwKICAgICAgICAgICAgICAgICAge3sjaGFzU2FtcGxlcnN9fXt7PiB3aXRoX3NhbXBsZXJfdW5pZm9ybXMuZGFydH19e3svaGFzU2FtcGxlcnN9fXt7Xmhhc1NhbXBsZXJzfX17ez4gd2l0aG91dF9zYW1wbGVyX3VuaWZvcm1zLmRhcnR9fXt7L2hhc1NhbXBsZXJzfX0KICAgICAgICAgICAgICAgICk7CiAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgICBjaGlsZDogRml0dGVkQm94KAogICAgICAgICAgICAgICAgY2hpbGQ6IENvbnRhaW5lcigKICAgICAgICAgICAgICAgICAgY29sb3I6IENvbG9ycy50cmFuc3BhcmVudCwKICAgICAgICAgICAgICAgICAgd2lkdGg6IGNvbnN0cmFpbnRzLm1heFdpZHRoLAogICAgICAgICAgICAgICAgICBoZWlnaHQ6IGNvbnN0cmFpbnRzLm1heEhlaWdodCwKICAgICAgICAgICAgICAgICksCiAgICAgICAgICAgICAgKSwKICAgICAgICAgICAgKTsKICAgICAgICAgIH0sCiAgICAgICAgKTsKICAgICAgfSwKICAgICk7CiAgfQp9Cgpjb25zdCBfc3BpcnYgPQogICAge3t7c3BpcnZCeXRlc319fTsK",
      "type": "text"
    },
    {
      "path": "{{~ with_sampler_uniforms.dart }}",
      "data":
          "c2FtcGxlclVuaWZvcm1zOiBbe3sjc2FtcGxlcnN9fQogICAgICAgICAgICAgICAgSW1hZ2VTaGFkZXIoCiAgICAgICAgICAgICAgICAgIF97e25hbWUuY2FtZWxDYXNlKCl9fXt7ZXh0ZW5zaW9ufX0sCiAgICAgICAgICAgICAgICAgIFRpbGVNb2RlLmNsYW1wLAogICAgICAgICAgICAgICAgICBUaWxlTW9kZS5jbGFtcCwKICAgICAgICAgICAgICAgICAgVW1icmFTaGFkZXIuaWRlbnRpdHksCiAgICAgICAgICAgICAgICApLHt7L3NhbXBsZXJzfX0KICAgICAgICAgICAgICBdLA==",
      "type": "text"
    },
    {
      "path": "{{~ without_sampler_uniforms.dart }}",
      "data": "c2FtcGxlclVuaWZvcm1zOiBbXSw=",
      "type": "text"
    }
  ],
  "hooks": [],
  "name": "flutter_widget_file",
  "description": "Generate a Flutter Widget file for a Flutter GLSL shader.",
  "version": "0.1.0+1",
  "environment": {"mason": ">=0.1.0-dev <0.1.0"},
  "vars": {}
});
