import 'dart:convert';
import 'dart:typed_data';
import 'dart:ui';

import 'package:flutter/material.dart' hide Image;
import 'package:umbra_flutter/umbra_flutter.dart';

/// {@template pixelation}
/// A Flutter Widget for the `pixelation` shader.
/// {@endtemplate}
class Pixelation extends StatelessWidget {
  /// {@macro pixelation}
  const Pixelation({
    Key? key,
    BlendMode blendMode = BlendMode.src,
    required double pixelSize,
    required Image image,
  })  : _blendMode = blendMode,
        _pixelSize = pixelSize,
        _image = image,
        super(key: key);

  static Future<FragmentProgram>? _cachedProgram;

  final BlendMode _blendMode;
  
  final double _pixelSize;

  final Image _image;

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<FragmentProgram>(
      future: _cachedProgram ??
          FragmentProgram.compile(
            spirv: Uint8List.fromList(base64Decode(_spirv)).buffer,
          ),
      builder: (context, snapshot) {
        if (snapshot.hasError) {
          // TODO: Add a error builder?
          return Text('${snapshot.error}');
        }
        if (!snapshot.hasData) {
          // TODO: Add a loading builder?
          return const CircularProgressIndicator();
        }
        final program = snapshot.data!;

        return LayoutBuilder(
          builder: (context, constraints) {
            return ShaderMask(
              blendMode: _blendMode,
              shaderCallback: (bounds) {
                return program.shader(
                  floatUniforms: Float32List.fromList([
                    _pixelSize,
                    bounds.size.width, 
                    bounds.size.height,
                  ]),
                  samplerUniforms: [
                ImageShader(
                  _image,
                  TileMode.clamp,
                  TileMode.clamp,
                  UmbraShader.identity,
                ),
              ],
                );
              },
              child: FittedBox(
                child: Container(
                  color: Colors.transparent,
                  width: constraints.maxWidth,
                  height: constraints.maxHeight,
                ),
              ),
            );
          },
        );
      },
    );
  }
}

const _spirv =
    'AwIjBwAAAQAKAA0AVAAAAAAAAAARAAIAAQAAAAsABgABAAAAR0xTTC5zdGQuNDUwAAAAAA4AAwAAAAAAAQAAAA8ABwAEAAAABAAAAG1haW4AAAAARwAAAE0AAAAQAAMABAAAAAgAAAADAAMAAQAAAEABAAAEAAoAR0xfR09PR0xFX2NwcF9zdHlsZV9saW5lX2RpcmVjdGl2ZQAABAAIAEdMX0dPT0dMRV9pbmNsdWRlX2RpcmVjdGl2ZQAFAAQABAAAAG1haW4AAAAABQAGAA0AAABwaXhlbCh2ZjI7dmYyOwAABQADAAsAAABwb3MABQADAAwAAAByZXMABQAHABEAAABmcmFnbWVudCh2ZjI7dmYyOwAAAAUAAwAPAAAAdXYAAAUABQAQAAAAZnJhZ0Nvb3JkAAAABQAEADEAAABpbWFnZQAAAAUABQA4AAAAcmVzb2x1dGlvbgAABQAFADsAAABwaXhlbFNpemUAAAAFAAQAPwAAAHBhcmFtAAAABQAEAEEAAABwYXJhbQAAAAUAAwBFAAAAdXYAAAUABgBHAAAAZ2xfRnJhZ0Nvb3JkAAAAAAUABABNAAAAX0NPTE9SXwAFAAQATgAAAHBhcmFtAAAABQAEAFAAAABwYXJhbQAAAEcAAwANAAAAAAAAAEcAAwALAAAAAAAAAEcAAwAMAAAAAAAAAEcAAwARAAAAAAAAAEcAAwAPAAAAAAAAAEcAAwAQAAAAAAAAAEcAAwATAAAAAAAAAEcAAwAUAAAAAAAAAEcAAwAVAAAAAAAAAEcAAwAWAAAAAAAAAEcAAwAXAAAAAAAAAEcAAwAYAAAAAAAAAEcAAwAdAAAAAAAAAEcAAwAfAAAAAAAAAEcAAwAgAAAAAAAAAEcAAwAjAAAAAAAAAEcAAwAkAAAAAAAAAEcAAwAlAAAAAAAAAEcAAwAmAAAAAAAAAEcAAwAxAAAAAAAAAEcABAAxAAAAHgAAAAEAAABHAAQAMQAAACIAAAAAAAAARwAEADEAAAAhAAAAAAAAAEcAAwAyAAAAAAAAAEcAAwAzAAAAAAAAAEcAAwA0AAAAAAAAAEcAAwA4AAAAAAAAAEcABAA4AAAAHgAAAAIAAABHAAMAOQAAAAAAAABHAAMAOwAAAAAAAABHAAQAOwAAAB4AAAAAAAAARwADADwAAAAAAAAARwADAD0AAAAAAAAARwADAD4AAAAAAAAARwADAD8AAAAAAAAARwADAEAAAAAAAAAARwADAEEAAAAAAAAARwADAEIAAAAAAAAARwADAEUAAAAAAAAARwAEAEcAAAALAAAADwAAAEcAAwBKAAAAAAAAAEcAAwBNAAAAAAAAAEcABABNAAAAHgAAAAAAAABHAAMATgAAAAAAAABHAAMATwAAAAAAAABHAAMAUAAAAAAAAABHAAMAUwAAAAAAAAATAAIAAgAAACEAAwADAAAAAgAAABYAAwAGAAAAIAAAABcABAAHAAAABgAAAAIAAAAgAAQACAAAAAcAAAAHAAAAFwAEAAkAAAAGAAAABAAAACEABQAKAAAACQAAAAgAAAAIAAAAFQAEABkAAAAgAAAAAAAAACsABAAZAAAAGgAAAAAAAAAgAAQAGwAAAAcAAAAGAAAAKwAEAAYAAAAeAAAAAAAAPysABAAZAAAAIQAAAAEAAAAUAAIAJwAAACsABAAGAAAAKwAAAAAAAAAsAAcACQAAACwAAAArAAAAKwAAACsAAAArAAAAGQAJAC4AAAAGAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAGwADAC8AAAAuAAAAIAAEADAAAAAAAAAALwAAADsABAAwAAAAMQAAAAAAAAAgAAQANwAAAAAAAAAHAAAAOwAEADcAAAA4AAAAAAAAACAABAA6AAAAAAAAAAYAAAA7AAQAOgAAADsAAAAAAAAAIAAEAEYAAAABAAAACQAAADsABABGAAAARwAAAAEAAAAgAAQATAAAAAMAAAAJAAAAOwAEAEwAAABNAAAAAwAAADYABQACAAAABAAAAAAAAAADAAAA+AACAAUAAAA7AAQACAAAAEUAAAAHAAAAOwAEAAgAAABOAAAABwAAADsABAAIAAAAUAAAAAcAAAA9AAQACQAAAEgAAABHAAAATwAHAAcAAABJAAAASAAAAEgAAAAAAAAAAQAAAD0ABAAHAAAASgAAADgAAACIAAUABwAAAEsAAABJAAAASgAAAD4AAwBFAAAASwAAAD0ABAAHAAAATwAAAEUAAAA+AAMATgAAAE8AAAA9AAQACQAAAFEAAABHAAAATwAHAAcAAABSAAAAUQAAAFEAAAAAAAAAAQAAAD4AAwBQAAAAUgAAADkABgAJAAAAUwAAABEAAABOAAAAUAAAAD4AAwBNAAAAUwAAAP0AAQA4AAEANgAFAAkAAAANAAAAAAAAAAoAAAA3AAMACAAAAAsAAAA3AAMACAAAAAwAAAD4AAIADgAAAD0ABAAHAAAAEwAAAAsAAAA9AAQABwAAABQAAAAMAAAAhQAFAAcAAAAVAAAAEwAAABQAAAAMAAYABwAAABYAAAABAAAACAAAABUAAAA9AAQABwAAABcAAAAMAAAAiAAFAAcAAAAYAAAAFgAAABcAAAA+AAMACwAAABgAAABBAAUAGwAAABwAAAALAAAAGgAAAD0ABAAGAAAAHQAAABwAAACDAAUABgAAAB8AAAAdAAAAHgAAAAwABgAGAAAAIAAAAAEAAAAEAAAAHwAAAEEABQAbAAAAIgAAAAsAAAAhAAAAPQAEAAYAAAAjAAAAIgAAAIMABQAGAAAAJAAAACMAAAAeAAAADAAGAAYAAAAlAAAAAQAAAAQAAAAkAAAADAAHAAYAAAAmAAAAAQAAACgAAAAgAAAAJQAAALoABQAnAAAAKAAAACYAAAAeAAAA9wADACoAAAAAAAAA+gAEACgAAAApAAAAKgAAAPgAAgApAAAA/gACACwAAAD4AAIAKgAAAD0ABAAvAAAAMgAAADEAAAA9AAQABwAAADMAAAALAAAAVwAFAAkAAAA0AAAAMgAAADMAAAD+AAIANAAAADgAAQA2AAUACQAAABEAAAAAAAAACgAAADcAAwAIAAAADwAAADcAAwAIAAAAEAAAAPgAAgASAAAAOwAEAAgAAAA/AAAABwAAADsABAAIAAAAQQAAAAcAAAA9AAQABwAAADkAAAA4AAAAPQAEAAYAAAA8AAAAOwAAAFAABQAHAAAAPQAAADwAAAA8AAAAiAAFAAcAAAA+AAAAOQAAAD0AAAA9AAQABwAAAEAAAAAPAAAAPgADAD8AAABAAAAAPgADAEEAAAA+AAAAOQAGAAkAAABCAAAADQAAAD8AAABBAAAA/gACAEIAAAA4AAEA';
