name: umbra_flutter
description: An accompanying Flutter library for generated Umbra shaders.
version: 0.1.0-dev.3
repository: https://github.com/wolfenrain/umbra

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0
