name: umbra_flutter
description: A Flutter library for generated Umbra shaders.
version: 0.1.0-dev.1
homepage: https://github.com/wolfenrain/umbra
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0
