name: umbra
description: The core functionality for Umbra shaders which that helps Flutter developers to generate the necessary files for Flutter Shaders.
version: 0.0.1-dev.1
repository: https://github.com/wolfenrain/umbra/tree/main/packages/umbra

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies: 
  equatable: ^2.0.3
  mason: ^0.1.0-dev.21

dev_dependencies:
  build_runner: ^2.1.11
  build_verify: ^3.0.0
  build_version: ^2.1.1
  coverage: ^1.1.0
  mocktail: ^0.3.0
  path: ^1.8.1
  test: ^1.19.2
  very_good_analysis: ^3.0.0
