name: umbra
description: The core functionality for Umbra shaders which that helps Flutter developers to generate the necessary files for Flutter Shaders.
version: 0.1.0-dev.1
repository: https://github.com/wolfenrain/umbra

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies: 
  equatable: ^2.0.3
  mason: ^0.1.0-dev.21

dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^0.3.0
  path: ^1.8.1
  test: ^1.19.2
  very_good_analysis: ^3.0.0
