name: umbra_cli
description: Umbra CLI allows Flutter developers to create their own shaders and compile them to strongly typed dart files.
version: 0.1.0-dev.5
repository: https://github.com/wolfenrain/umbra

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  archive: ^3.3.0
  args: ^2.3.0
  collection: ^1.16.0
  mason: ^0.1.0-dev.23
  meta: ^1.7.0
  path: ^1.8.1
  pub_updater: ^0.2.2
  umbra: ^0.1.0-dev.2

dev_dependencies:
  build_runner: ^2.1.11
  build_verify: ^3.0.0
  build_version: ^2.1.1
  coverage: ^1.1.0
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^3.0.0

executables:
  umbra: umbra