name: umbra_cli
description: Command Line Interface for Umbra.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  archive: ^3.3.0
  args: ^2.3.0
  mason: ^0.1.0-dev.21
  meta: ^1.7.0
  path: ^1.8.1
  pub_updater: ^0.2.2
  umbra_core:
    path: ../umbra_core

dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0

executables:
  umbra: umbra