name: umbra_cli

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/umbra_cli.yaml
      - packages/umbra_cli/**

  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/umbra_cli.yaml
      - packages/umbra_cli/**

jobs:
  setup:
    defaults:
      run:
        working-directory: packages/umbra_cli

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        run: dart pub get

      - name: Format
        run: dart format --set-exit-if-changed lib

      - name: Analyze
        run: dart analyze --fatal-infos --fatal-warnings .

      - name: Ensure Build
        run: dart test --run-skipped -t pull-request-only

  build:
    needs: setup

    defaults:
      run:
        working-directory: packages/umbra_cli

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        run: dart pub get

      - name: Run Tests
        run: |
          dart pub global activate coverage 1.2.0
          dart test -j 1 -x pull-request-only --coverage=coverage && dart pub global run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.packages --report-on=lib

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1
        with:
          path: packages/umbra_cli/coverage/lcov.info

  pana:
    defaults:
      run:
        working-directory: packages/umbra_cli

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        run: |
          dart pub get
          dart pub global activate pana

      - name: Verify Pub Score
        run: ../../tools/verify_pub_score.sh