name: umbra_flutter

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/umbra_flutter.yaml
      - packages/umbra_flutter/**

  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/umbra_flutter.yaml
      - packages/umbra_flutter/**

jobs:
  build:
    defaults:
      run:
        working-directory: packages/umbra_flutter

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.0.0
          channel: stable
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Format
        run: flutter format --set-exit-if-changed lib test

      - name: Analyze
        run: flutter analyze lib test

      - name: Run Tests
        run: flutter test --test-randomize-ordering-seed random

      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1
        with:
          path: packages/umbra_flutter/coverage/lcov.info

  pana:
    defaults:
      run:
        working-directory: packages/umbra_flutter

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        run: |
          dart pub get
          dart pub global activate pana

      - name: Verify Pub Score
        run: ../../tools/verify_pub_score.sh