name: umbra_flutter

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths:
      - "packages/umbra_flutter/**"
      - ".github/workflows/umbra_flutter.yaml"

  pull_request:
    paths:
      - "packages/umbra_flutter/**"
      - ".github/workflows/umbra_flutter.yaml"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      working_directory: packages/umbra_flutter
